import keyboard
import time

delay=0.1
print("Tails1154 Commander KEEN 1 thing")
print("Starting in 3 seconds...")
time.sleep(3)
print("Starting!")
def enter():
    keyboard.press_and_release('enter')
def jump():
    keyboard.press('ctrl')
    time.sleep(0.5)
    keyboard.release('ctrl')
def pogo():
    keyboard.press_and_release('alt')
def startgame():
    print("Attempting to start commander keen")
    keyboard.write("C:", delay=delay)
    keyboard.press_and_release('enter')
    keyboard.write("cd keen", delay=delay)
    enter()
    keyboard.write("keen1.exe", delay=delay)
    enter()
    print("Waiting for keen1.exe to load")
    time.sleep(10)
def newgame():
    print("Starting new game")
    time.sleep(1)
    enter()
    time.sleep(1)
    enter()
    time.sleep(1)
    enter()
def keenclosekeen():
    print("Closing keens left screen")
    time.sleep(1)
    enter()
    time.sleep(1)
def enterlevel1():
    print("Trying to enter level 1")
    keyboard.press('down')
    time.sleep(0.5)
    keyboard.release('down')
    time.sleep(0.5)
    keyboard.press('right')
    time.sleep(2)
    keyboard.release('right')
    time.sleep(0.5)
    keyboard.press('ctrl')
    time.sleep(0.5)
    keyboard.release('ctrl')
def beatlevel1():
    print("Trying to beat level 1!")
    keyboard.press('right')
    time.sleep(1)
    print("1")
    jump()
    time.sleep(3)
    print("2")
    jump()
    time.sleep(2)
    print("3")
    jump()
    time.sleep(5)
    print("4")
    jump()
    time.sleep(1)
    print("5")
    jump()
    time.sleep(1)
    print("6")
    jump()
    time.sleep(1.5)
    print("7")
    jump()
    time.sleep(1)
    print("8")
    jump()
    time.sleep(2)
    print("9")
    jump()
    time.sleep(2)
    print("10")
    jump()
    time.sleep(1)
    print("11")
    jump()
    print("12")
    jump()
    time.sleep(1)
    print("13")
    jump()
    while True:
        1+1
startgame()
newgame()
keenclosekeen()
enterlevel1()
beatlevel1()
print("Done!")
